// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config as loadEnv } from 'dotenv';
import { defineConfig } from "prisma/config";

loadEnv({ path: '.env.local' });
loadEnv();

if (!process.env.DATABASE_URL) {
  throw new Error('DATABASE_URL is required for Prisma commands. Set it in .env.local or the shell environment.');
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx ./prisma/seed.ts",
  },
  datasource: {
    url: process.env.DATABASE_URL,
  },
});
