// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config as loadEnv } from 'dotenv';
import { defineConfig } from "prisma/config";

loadEnv({ path: '.env.local' });
loadEnv();

// Use a fallback DATABASE_URL for build-time Prisma generation
// This is needed because Docker containers don't have env vars during build
const databaseUrl = process.env.DATABASE_URL || 'postgresql://user:password@localhost:5432/amakuru_db';

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx ./prisma/seed.ts",
  },
  datasource: {
    url: databaseUrl,
  },
});
