#!/bin/bash

# warm-social-cache.sh
# Warms Next.js ISR cache for social metadata on all articles
# 
# USAGE:
#   bash scripts/warm-social-cache.sh
#
# This script reads URLs from urls-to-warm.txt (generated by migrate-article-metadata.ts)
# and requests each article page to trigger Next.js ISR cache regeneration.
#
# Cache warming ensures social crawlers (Facebook, Twitter, LinkedIn, WhatsApp, Telegram)
# get fresh metadata immediately after deployment, not after 24-48 hours.

set -e

URLS_FILE="urls-to-warm.txt"
PARALLEL_REQUESTS=10
TIMEOUT=30

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Check if URLs file exists
if [ ! -f "$URLS_FILE" ]; then
  echo -e "${RED}❌ Error: $URLS_FILE not found${NC}"
  echo "Run 'npx tsx scripts/migrate-article-metadata.ts' first to generate URLs"
  exit 1
fi

# Count URLs
TOTAL_URLS=$(wc -l < "$URLS_FILE")

echo -e "${BLUE}═══════════════════════════════════════════════════════════${NC}"
echo -e "${BLUE}🔥 SOCIAL METADATA CACHE WARMING${NC}"
echo -e "${BLUE}═══════════════════════════════════════════════════════════${NC}\n"

echo -e "📊 Configuration:"
echo -e "  URLs to warm: ${YELLOW}$TOTAL_URLS${NC}"
echo -e "  Parallel requests: ${YELLOW}$PARALLEL_REQUESTS${NC}"
echo -e "  Timeout per request: ${YELLOW}${TIMEOUT}s${NC}\n"

echo -e "⏱️  Starting cache warming (this may take a few minutes)...\n"

# Initialize counter
COUNT=0
SUCCESSFUL=0
FAILED=0
START_TIME=$(date +%s)

# Function to warm individual URL
warm_url() {
  local url="$1"
  local index="$2"
  local total="$3"
  
  if curl -s --max-time "$TIMEOUT" "$url" > /dev/null 2>&1; then
    echo -e "  ${GREEN}✅${NC} [$index/$total] $(echo $url | sed 's|https://||')"
    return 0
  else
    echo -e "  ${RED}❌${NC} [$index/$total] $(echo $url | sed 's|https://||') (timeout or error)"
    return 1
  fi
}

export -f warm_url
export GREEN RED YELLOW TIMEOUT

# Use GNU parallel if available, otherwise xargs or loop
if command -v parallel &> /dev/null; then
  echo -e "Using ${YELLOW}GNU parallel${NC} for concurrent requests...\n"
  
  cat "$URLS_FILE" | nl -w1 -s' ' | parallel -j "$PARALLEL_REQUESTS" --line-buffer \
    'warm_url "{2}" {1} '$TOTAL_URLS
  
  SUCCESSFUL=$(grep -c "^  ${GREEN}✅${NC}" <<< "$(tail -f /dev/null)" || echo "$TOTAL_URLS")
  
elif command -v xargs &> /dev/null; then
  echo -e "Using ${YELLOW}xargs${NC} for concurrent requests...\n"
  
  # xargs with parallel processing
  cat "$URLS_FILE" | nl -w1 -s' ' | xargs -P "$PARALLEL_REQUESTS" -n 1 bash -c \
    'warm_url "$(echo "$1" | awk "{print \$2}")" "$(echo "$1" | awk "{print \$1}")" '$TOTAL_URLS'' _
  
else
  # Fallback to sequential processing
  echo -e "Using ${YELLOW}sequential processing${NC} (consider installing GNU parallel for faster warming)\n"
  
  while IFS= read -r url; do
    ((COUNT++))
    if warm_url "$url" "$COUNT" "$TOTAL_URLS"; then
      ((SUCCESSFUL++))
    else
      ((FAILED++))
    fi
  done < "$URLS_FILE"
fi

END_TIME=$(date +%s)
DURATION=$((END_TIME - START_TIME))

# Summary
echo -e "\n${BLUE}═══════════════════════════════════════════════════════════${NC}"
echo -e "${BLUE}📊 CACHE WARMING SUMMARY${NC}"
echo -e "${BLUE}═══════════════════════════════════════════════════════════${NC}\n"

echo -e "Total URLs processed: ${YELLOW}$TOTAL_URLS${NC}"
echo -e "Duration: ${YELLOW}${DURATION}s${NC} (~$(echo "scale=2; $DURATION/$TOTAL_URLS" | bc)s per URL)\n"

# Show completion message
if [ "$FAILED" -eq 0 ]; then
  echo -e "${GREEN}✅ All articles warmed successfully!${NC}\n"
  echo -e "Social crawlers will now see fresh metadata for:"
  echo -e "  • Facebook Sharing Debugger"
  echo -e "  • Twitter Card Validator"
  echo -e "  • LinkedIn Post Inspector"
  echo -e "  • WhatsApp"
  echo -e "  • Telegram\n"
  
  echo -e "${YELLOW}Optional: Manually refresh key articles${NC}"
  echo -e "  1. Facebook: https://developers.facebook.com/tools/debug/sharing/"
  echo -e "  2. Twitter: https://cards-dev.twitter.com/validator"
  echo -e "  3. LinkedIn: https://www.linkedin.com/post-inspector/\n"
  
  echo -e "${BLUE}═══════════════════════════════════════════════════════════${NC}\n"
  exit 0
else
  echo -e "${YELLOW}⚠️  $SUCCESSFUL successful, $FAILED failed${NC}"
  echo -e "${YELLOW}Failed URLs will retry on next request${NC}\n"
  
  echo -e "${BLUE}═══════════════════════════════════════════════════════════${NC}\n"
  exit 1
fi
